---
    - name: Creating Directory
      ansible.builtin.file:
        path: /srv/www
        state: directory
        group: www-data
        owner: www-data
      become: yes

    - name: Download and unzip
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: true
      become: yes

    - name: Configuring Apache (seding file to server)
      ansible.builtin.template:
        src: templates/wordpress.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - Restart apache

    - name: Copying sample configuration file
      ansible.builtin.copy:
        src: "{{ wp_dir }}/wp-config-sample.php"
        dest: "{{ wp_dir }}/wp-config.php"
        force: no
        remote_src: yes
      become: yes

    - name: Replacing with database informations
      ansible.builtin.replace:
        path: "{{ wp_dir }}/wp-config.php"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
      - {regexp: "database_name_here", replace: "{{ wp_db_name }}"}
      - {regexp: "username_here", replace: "{{ wp_db_user }}"}
      - {regexp: "password_here", replace: "{{ wp_db_password }}"}
      - {regexp: "localhost", replace: "{{ wp_db_host }}"}
      become: yes

    - name: Getting new salts from WordPress API
      ansible.builtin.uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: yes
      register: wp_salts

    - name: Configuring file to “known secrets” attacks
      ansible.builtin.replace:
        path: "{{ wp_dir }}/wp-config.php"
        regexp: "(?s)define\\( 'AUTH_KEY'.*define\\( 'NONCE_SALT',\\s+'put your unique phrase here' \\);"
        replace: "{{ wp_salts.content }}"
      become: yes

    # - name: Configuring file to “known secrets” attacks
    #   ansible.builtin.lineinfile:
    #     path: "{{ wp_dir }}/wp-config.php"
    #     search_string: "{{ item.search_string }}"
    #     line: "{{ item.line }}"
    #   with_items:
    #   - {search_string: "define( 'AUTH_KEY',         'put your unique phrase here' );", line: "define('AUTH_KEY',         '+#X4]rw+3U6UNY!%|!:rR[3n%.+=<5CZ%{P$o?2K:&^ssU!dNJ|IN99rmdFfL&fV');"}
    #   - {search_string: "define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );", line: "define('SECURE_AUTH_KEY',  'Qp6Y)|=Bu%S>OmGjICAK!H+:{>)jJ13.p~IsW_k7hZ+l!ix%t!Tr,i-,!)e%(H.M');"}
    #   - {search_string: "define( 'LOGGED_IN_KEY',    'put your unique phrase here' );", line: "define('LOGGED_IN_KEY',    '^,lN=fW9<jS[&gBX#{YpuJH8&/&-6N1;!Op/bBXUA6/)$9;gbCWDi |:*?j51`la');"}
    #   - {search_string: "define( 'NONCE_KEY',        'put your unique phrase here' );", line: "define('NONCE_KEY',        '-(atC%a90 {47:?lP:nAY!Ugu?huf>mYz|6 &.MNuSv+=ko8ml>v9t|+e5wU2)d&');"}
    #   - {search_string: "define( 'AUTH_SALT',        'put your unique phrase here' );", line: "define('AUTH_SALT',        '|4_/wQ-]`c!ak7d.(3R2!))4,LiOARE({do0Sn>v.|SR;Oer.mHFFQ&!J_4C:2^)');"}
    #   - {search_string: "define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );", line: "define('SECURE_AUTH_SALT', '0Y!&;mT-XCk7i%bY~GAOVg04/l;Nf/EYsQX`pOcJtS}![fQIfgfR5IR^&743q T&');"}
    #   - {search_string: "define( 'LOGGED_IN_SALT',   'put your unique phrase here' );", line: "define('LOGGED_IN_SALT',   '4`JL_C;IvFFg>g|+04)a,A``=sY},f~ 1`;k2khLeM]BheXP._5-@_516(&W-1PB');"}
    #   - {search_string: "define( 'NONCE_SALT',       'put your unique phrase here' );", line: "define('NONCE_SALT',       'Nl(o.z22[tlRo@_:+9>kF%g|lY=;;W7Lic6!}3(N$?{NzYuC|(e^B5y31cso7#8+');"}
    #   become: yes