---
    - name: Install dependences
      ansible.builtin.apt:
        pkg:
          - mysql-server 
          - python3-pymysql
        update_cache: yes
        state: latest
      become: yes

    - name: creating db (wordpress_db)
      community.mysql.mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: creating user (wordpress_user)
      community.mysql.mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: "{{ item }}"
      with_items:
        - "localhost"
        - "127.0.0.1"
        - "{{ wp_ip }}"
      become: yes

    - name: Configuring MySQL to listen on all interfaces
      ansible.builtin.replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
      become: yes
      notify:
        - Restart mysql